org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# 开启 Gradle 构建缓存（核心！解决你的日志问题）
org.gradle.caching=true
# 可选：开启缓存调试日志，能看到缓存命中情况
org.gradle.caching.debug=true
